group: edge
sudo: required

language: go
go:
  - 1.10.x
  - 1.11.x

services:
  - docker

env:
  - GO111MODULE=on

install:
  - go get -u github.com/golang/lint/golint

matrix:
  include:
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: go test -v -mod=vendor ./...

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make docker-build
  - make docker-push
