group: edge
sudo: required

language: go
go: 
  - 1.6.3

services: 
  - docker

install:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - go test -race -v $(go list ./... | grep -v /vendor/)
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o goddd .

after_success:
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME 
  - docker push $DOCKER_IMAGE_NAME
